#!/bin/sh

. /etc/rc.subr

name=buildbotd
rcvar=buildbotd_enable

command="/usr/bin/su"
command_args="-m buildslave -l -c '/usr/local/bin/python2 /usr/local/bin/buildslave start --nodaemon /buildslave/'"

load_rc_config $name
run_rc_command "$1"
