#!/bin/sh

. /etc/rc.subr

name=buildbotd
rcvar=buildbotd_enable

pidfile="/buildslave/twistd.pid"

command="/usr/bin/su"
command_args="-l buildslave -c '/buildslave/venv/bin/python2 /buildslave/venv/bin/buildslave start /buildslave/'"

load_rc_config $name
run_rc_command "$1"
